sudo: required

language: java
jdk: openjdk11

services: docker

before_script:
  - docker run --name postgres -p 6543:5432 -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_password -d postgres
  - docker ps


