sudo: required

language: java
jdk: openjdk11

services: docker

before_script:
  - docker run --name postgres -p 6543:5432 -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_password -e POSTGRES_DB=testdb -d postgres

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: test
      script: mvn test -B
    - stage: package
      script: mvn package -B
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: "158ce801d6475539f3a98d22066719c83eedc730"
        skip_cleanup: true
        on:
          tags: true

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name drunkmowgli
  - git config --local user.email drunkmowgli@gmail.com

#deploy:
#  provider: releases
#  overwrite: true
#  api_key: "158ce801d6475539f3a98d22066719c83eedc730"
#  file_glob: true
#  file: "target/Bookshell-1.0.$TRAVIS_TAG.jar"
#  skip_cleanup: true
#  on:
#    branch: master
