sudo: required

language: java
jdk: openjdk11

services: docker

before_script:
  - docker run --name postgres -p 6543:5432 -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_password -e POSTGRES_DB=testdb -d postgres

cache:
  directories:
    - $HOME/.m2

before_deploy:
  - mvn clean
  - mvn package
  - git config --local user.name "drunkmowgli"
  - git config --local user.email "drunkmowgli@gmail.com"
  - export NAME="v$(git rev-parse HEAD)"
  - git tag $NAME

jobs:
  include:
    - stage: test
      script: mvn test -B
    - stage: package
      script: mvn package -B
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        - provider: releases
          api_key: "158ce801d6475539f3a98d22066719c83eedc730"
          file_glob: true
          file: "target/Bookshell-*.jar"
          skip_cleanup: true
          name: $NAME
          on:
            branch: master
            jdk: oraclejdk11


#deploy:
#  provider: releases
#  overwrite: true
#  api_key: "158ce801d6475539f3a98d22066719c83eedc730"
#  file_glob: true
#  file: "target/Bookshell-1.0.$TRAVIS_TAG.jar"
#  skip_cleanup: true
#  on:
#    branch: master
