sudo: required

language: java
jdk: openjdk11

services: docker

before_script:
  - docker run --name postgres -p 6543:5432 -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_password -e POSTGRES_DB=testdb -d postgres

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: test
      script: mvn test -B
    - stage: package
      script: mvn package -B
    - stage: deploy

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name drunkmowgli
      - git config --local user.email drunkmowgli@gmail.com
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "158ce801d6475539f3a98d22066719c83eedc730"
  file_glob: true
  file: "target/Bookshell-*.jar"
  skip_cleanup: true
  on:
    branch: feature/ci
    tags: true