spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/bookshell
    username: prod_user
    password: prod_password